<?php
function deviation_serialnumbers_page_build(&$page) {
# here should go serial number display or
}

function deviation_serialnumbers_node_insert($node){
  $msg  = "node saved: ";
  $msg .= _deviation_serialnumbers_find_max($node->nid);
  $msg .= print_r(node_type_get_names(), true);
  drupal_set_message($msg);
}

function _deviation_serialnumbers_find_max($nid) {
  return $nid;
}

/**
 * Implements hook_menu().
 */
function deviation_serialnumbers_menu() {
  $items = array();

  $items['admin/config/deviation_serialnumbers'] = array(
    'title' => 'Current posts',
    'description' => 'Configuration for Current posts module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deviation_serialnumbers_admin_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: Current posts settings
 *
 * @see current_posts_menu()
 */
function deviation_serialnumbers_admin_form($form, &$form_state) {
  $options = node_type_get_names();

  $form['deviation_serialnumbers_content_type'] = array(
    '#title' => t('Content types where to add serialnumbers'),
    '#type' => 'checkboxes',
    '#description' => t(''),
    '#options' => $options,
    '#default_value' => variable_get(
      'deviation_serialnumbers_content_type', 3
    ),
  );
  return system_settings_form($form);
}
